steps:
- label: Hello World!
  command: echo Hello World!
  agents:
    queue: kubernetes
  plugins:
    - kubernetes:
        gitEnvFrom:
          - secretRef:
              name: my-git-ssh-credentials
        podSpec:
          containers:
            - image: gradle:latest
              command: [gradle]
              args:
                - jib
                - --image=ttl.sh/example:1h
