steps:
- label: Hello World!
  command: echo Hello World!
  agents:
    queue: kubernetes
  plugins:
    - kubernetes:
        checkout:
          gitCredentialsSecret:
            secretName: my-git-credentials
        podSpec:
          containers:
            - image: gradle:latest
              command: [gradle]
              args:
                - jib
                - --image=ttl.sh/example:1h
