steps:
- label: Hello World!
  command: echo Hello World!
  agents:
    queue: kubernetes
  plugins:
    - kubernetes:
        gitEnvFrom:
          - secretRef:
            name: my-git-ssh-credentials
        podSpec:
          containers:
            - image: alpine:latest
              command: 
                - echo Hello World!
