steps:
- label: Hello World!
  agents:
    queue: kubernetes
  plugins:
    - kubernetes:
        checkout:
          gitCredentialsSecret:
            secretName: my-git-credentials
        podSpec:
          containers:
            - image: alpine:latest
              command: 
                - echo Hello World!
