steps:
- label: Hello World!
  command: echo Hello World!
  agents:
    queue: kubernetes
  plugins:
    - kubernetes:
        gitEnvFrom:
          - secretRef:
            name: my-git-ssh-credentials
        podSpec:
          containers:
            - image: alpine:latest
              command: [kubectl]
              args:
                - "version"
                - "--short"
              resources:
                limits:
                  cpu: "100m"
                  memory: "128Mi"
